/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MenuAudiencias {
    }
}
declare global {
    interface HTMLMenuAudienciasElement extends Components.MenuAudiencias, HTMLStencilElement {
    }
    var HTMLMenuAudienciasElement: {
        prototype: HTMLMenuAudienciasElement;
        new (): HTMLMenuAudienciasElement;
    };
    interface HTMLElementTagNameMap {
        "menu-audiencias": HTMLMenuAudienciasElement;
    }
}
declare namespace LocalJSX {
    interface MenuAudiencias {
    }
    interface IntrinsicElements {
        "menu-audiencias": MenuAudiencias;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "menu-audiencias": LocalJSX.MenuAudiencias & JSXBase.HTMLAttributes<HTMLMenuAudienciasElement>;
        }
    }
}
